---
version: '3'
services:
  api:
    container_name: api
    build: .
    restart: on-failure
    volumes:
      - ./:/app/api
    env_file: .env
    environment:
      - API_PORT=${API_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_ADDR=postgres
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - postgres
      - redis
      - adminer
      - migrate
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: on-failure
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  redis:
    container_name: redis
    image: redis:alpine
    restart: on-failure
    volumes:
      - ./data/redis:/data
    env_file: .env
    ports:
      - 6379:6379
  adminer:
    container_name: adminer
    image: adminer:standalone
    restart: on-failure
    ports:
      - 8080:8080
  migrate:
    image: migrate/migrate
    restart: on-failure
    volumes:
      - ./db/migrations:/migrations
    command:
      [
        '-path',
        '/migrations',
        '-database',
        'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}?sslmode=disable',
        'up',
      ]
    depends_on:
      - postgres
